sudo: false
cache: bundler
language: node_js
node_js:
  - '0.10'
branches:
  only:
    - master
before_install:
  - npm install -g grunt-cli bower
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "biasiolije@gmail.com"
  - git config --global user.name "biasiolije"
  - bower install
script: ./run-tests.sh
after_success:
  - git clone https://www.github.com/biasiolije/bower-unesp-foundation.git
  - rm -rf bower-unesp-foundation/*
  - cd bower-unesp-foundation
  - touch deu_certo.txt
  - git remote rm origin
  - git remote add origin https://biasiolije:${GH_TOKEN}@github.com/biasiolije/bower-unesp-foundation.git
  - git add -A
  - git commit -m "Unesp Foundation build para o bower"
  - git push -fq origin master
  - git push -fq origin --tags
  - echo -e "A mágica acabou\n"
notifications:
  email:
    recipients:
      - biasiolije@gmail.com